security:
firewalls:

    main:
        pattern: ^/
        form_login:
            provider: fos_userbundle
            csrf_token_generator: security.csrf.token_manager
            login_path: /
            success_handler: redirect.after.login
            always_use_default_target_path: true
            default_target_path:            /login_check


            # if you are using Symfony < 2.8, use the following config instead:
            # csrf_provider: form.csrf_provider

        logout:       true
        anonymous:    true
        anonymous: ~
